# Generated by Django 4.0.6 on 2022-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_createlogin_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlogin',
            name='City',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createlogin',
            name='Course',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createlogin',
            name='Dob',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='createlogin',
            name='Email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createlogin',
            name='Gender',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createlogin',
            name='Pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createlogin',
            name='State',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
