# Generated by Django 4.0.6 on 2022-07-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_createlogin_city_createlogin_course_createlogin_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlogin',
            name='Dob',
            field=models.DateTimeField(blank=True),
        ),
    ]
