# Generated by Django 4.0.6 on 2022-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_createlogin_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlogin',
            name='Dob',
            field=models.DateField(blank=True),
        ),
    ]
