# Generated by Django 4.0.6 on 2022-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_createlogin_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlogin',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
