# Generated by Django 4.1.1 on 2022-09-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_createlogin_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlogin',
            name='CourseId',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
